error: circular dependency
- Migrated to multi module.
- More refactor to come. We are getting circular dependency error, and
  the app crashes on launch.